export const events = [
    {
        "age": "Ages 11 to 13",
        "agefltr": true,
        "cost": "FREE",
        "date": "17th October 2020",
        "datefltr": true,
        "description": "We take pride in our adaptability and believe we can impact every player, helping them reach their goals in, and out, of the world of Football.",
        "eventsTitle": "Strike 9 VLU October School Sessions",
        "eventsType": "Girls Sessions",
        "eventsTypefltr": true,
        "slots": 100,
        "time": "12:00 - 14:00",
        "timefltr": true        
    }, 
    {
        "age": "Ages 11 to 13",
        "agefltr": true,
        "cost": "FREE",
        "eventsTitle": "Strike 9 VLU October School Sessions",
        "eventsType": "Boys Sessions",
        "eventsTypefltr": true,        
        "date": "17th October 2020",
        "datefltr": true,
        "description": "We take pride in our adaptability and believe we can impact every player, helping them reach their goals in, and out, of the world of Football.",
        "slots": 100,
        "time": "12:00 - 14:00",
        "timefltr": true
    },
    {
        "age": "Ages 11 to 13",
        "agefltr": true,
        "cost": "FREE",
        "eventsTitle": "Strike 9 VLU October School Sessions",
        "eventsType": "Mixed Sessions",
        "eventsTypefltr": true,
        "date": "17th October 2020",
        "datefltr": true,
        "description": "We take pride in our adaptability and believe we can impact every player, helping them reach their goals in, and out, of the world of Football.",
        "slots": 100,
        "time": "12:00 - 14:00",
        "timefltr": true
    },
    {
        "age": "Ages 14 to 16",
        "agefltr": true,
        "cost": "FREE",
        "date": "20th October 2020",
        "datefltr": true,
        "description": "We take pride in our adaptability and believe we can impact every player, helping them reach their goals in, and out, of the world of Football.",
        "eventsTitle": "Strike 9 VLU October School Sessions",
        "eventsType": "Girls Sessions",
        "eventsTypefltr": true,
        "slots": 100,
        "time": "12:00 - 14:00",
        "timefltr": true        
    }, 
    {
        "age": "Ages 14 to 16",
        "agefltr": true,
        "cost": "FREE",
        "eventsTitle": "Strike 9 VLU October School Sessions",
        "eventsType": "Boys Sessions",
        "eventsTypefltr": true,        
        "date": "20th October 2020",
        "datefltr": true,
        "description": "We take pride in our adaptability and believe we can impact every player, helping them reach their goals in, and out, of the world of Football.",
        "slots": 100,
        "time": "12:00 - 14:00",
        "timefltr": true
    },
    {
        "age": "Ages 14 to 16",
        "agefltr": true,
        "cost": "FREE",
        "eventsTitle": "Strike 9 VLU October School Sessions",
        "eventsType": "Mixed Sessions",
        "eventsTypefltr": true,
        "date": "20th October 2020",
        "datefltr": true,
        "description": "We take pride in our adaptability and believe we can impact every player, helping them reach their goals in, and out, of the world of Football.",
        "slots": 100,
        "time": "12:00 - 14:00",
        "timefltr": true
    },
    {
        "age": "Ages 17 to 18",
        "agefltr": true,
        "cost": "FREE",
        "date": "27th October 2020",
        "datefltr": true,
        "description": "We take pride in our adaptability and believe we can impact every player, helping them reach their goals in, and out, of the world of Football.",
        "eventsTitle": "Strike 9 VLU October School Sessions",
        "eventsType": "Girls Sessions",
        "eventsTypefltr": true,
        "slots": 100,
        "time": "14:00 - 16:00",
        "timefltr": true        
    }, 
    {
        "age": "Ages 17 to 18",
        "agefltr": true,
        "cost": "FREE",
        "eventsTitle": "Strike 9 VLU October School Sessions",
        "eventsType": "Boys Sessions",
        "eventsTypefltr": true,        
        "date": "27th October 2020",
        "datefltr": true,
        "description": "We take pride in our adaptability and believe we can impact every player, helping them reach their goals in, and out, of the world of Football.",
        "slots": 100,
        "time": "14:00 - 16:00",
        "timefltr": true
    },
    {
        "age": "Ages 17 to 18",
        "agefltr": true,
        "cost": "FREE",
        "eventsTitle": "Strike 9 VLU October School Sessions",
        "eventsType": "Mixed Sessions",
        "eventsTypefltr": true,
        "date": "27th October 2020",
        "datefltr": true,
        "description": "We take pride in our adaptability and believe we can impact every player, helping them reach their goals in, and out, of the world of Football.",
        "slots": 100,
        "time": "14:00 - 16:00",
        "timefltr": true
    }    

]